warning_threshold: 5
disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - line_length
  - unused_closure_parameter
  - redundant_optional_initialization
  - function_body_length
  - cyclomatic_complexity
  - force_cast
  - unused_setter_value
excluded: # paths to ignore during linting. overridden by `included`.
  - Pods
